# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Thomas Pethick
author: Thomas Pethick
logo: ''

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _references/references.bib
  - _references/2018-05-22-io-model.bib
  - _references/2019-11-02-FTRL.bib
  - _references/2019-11-03-russell-talk.bib
  - _references/2020-01-06-hedge-and-bandit.bib
  - _references/2020-01-07-gp-mw.bib
  - _references/2020-05-26-bayesian-logistic-regression.bib
  - _references/2020-06-04-acceleration-perspectives.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  #extra_navbar: <div class="navbar_extra_footer">Theme by the <a href="https://ebp.jupyterbook.org">EBP</a></div>
sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_jinja

  config:
    language: en # necessary for hyphens to work
    bibtex_reference_style: author_year
    html_extra_path: ['assets']

    html_theme_options:
      search_bar_text: "Search..."
      use_download_button: false
      use_fullscreen_button: false

      # Makes footnotes Tufte-style sidenotes
      # (see https://sphinx-book-theme.readthedocs.io/en/stable/content-blocks.html?highlight=sidenote#activate-sidenotes-and-marginnotes)
      use_sidenotes: True

    html_sidebars:
      "**":
        - sidebar-logo.html
        - search-field.html
        - "sbt-sidebar-nav.html"
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

