###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Thomas Pethick'
bibtex_bibfiles = ['_references/references.bib', '_references/2018-05-22-io-model.bib', '_references/2019-11-02-FTRL.bib', '_references/2019-11-03-russell-talk.bib', '_references/2020-01-06-hedge-and-bandit.bib', '_references/2020-01-07-gp-mw.bib', '_references/2020-05-26-bayesian-logistic-regression.bib', '_references/2020-06-04-acceleration-perspectives.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2022'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'README.md', 'Thumbs.db', '_build', '_tikz/README.md']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 30
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_proof', 'sphinx_jinja', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css', 'font/cm/Serif/cmun-serif.css', 'font/cm/Sans/cmun-sans.css']
html_extra_path = ['assets']
html_favicon = ''
html_logo = ''
html_sidebars = {'**': ['sidebar-logo.html', 'search-field.html', 'sbt-sidebar-nav.html']}
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search...', 'use_download_button': False, 'use_fullscreen_button': False, 'use_sidenotes': True}
html_title = 'Thomas Pethick'
jupyter_cache = ''
jupyter_execute_notebooks = 'force'
language = 'en'
latex_engine = 'pdflatex'
myst_enable_extensions = ['amsmath', 'dollarmath', 'substitution']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True


# ablog configuration
import ablog
extensions = ["ablog"] + extensions
fontawesome_included = True
blog_path = "posts"
blog_title = "Thomas Pethick's blog"
blog_baseurl = "https://pethick.dk/"
blog_feed_archives = True
github_pages = "tmpethick"

# Populate publication context for jinja template
import yaml
with open("publications.yml", "r") as stream:
    publications = yaml.safe_load(stream)
jinja_contexts = {
  'publications_ctx': {'publications': publications}
}

# Makes footnotes Tufte-style sidenotes
# (see https://sphinx-book-theme.readthedocs.io/en/stable/content-blocks.html?highlight=sidenote#activate-sidenotes-and-marginnotes)
html_theme_options['use_sidenotes'] = True
