###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Thomas Pethick'
bibtex_bibfiles = ['_references/references.bib', '_references/2018-05-22-io-model.bib', '_references/2019-11-02-FTRL.bib', '_references/2019-11-03-russell-talk.bib', '_references/2020-01-06-hedge-and-bandit.bib', '_references/2020-01-07-gp-mw.bib', '_references/2020-05-26-bayesian-logistic-regression.bib', '_references/2020-06-04-acceleration-perspectives.bib', '_references/2024-06-10-polyak-stepsize.bib', '_references/2025-07-06-one-change-at-a-time.bib', '_references/2026-05-13-weight-decay-last-layer.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2022'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'README.md', 'Thumbs.db', '_build', '_tikz/README.md']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_proof', 'sphinx_jinja', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css', 'font/cm/Serif/cmun-serif.css', 'font/cm/Sans/cmun-sans.css']
html_extra_path = ['assets']
html_favicon = ''
html_js_files = ['custom.js']
html_logo = ''
html_sidebars = {'**': ['navbar-logo.html', 'search-field.html', 'sbt-sidebar-nav.html']}
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search...', 'use_download_button': False, 'use_fullscreen_button': False, 'use_sidenotes': True}
html_title = 'Thomas Pethick'
language = 'en'
latex_engine = 'pdflatex'
myst_enable_extensions = ['amsmath', 'dollarmath', 'substitution', 'colon_fence']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True

import datetime
import re

# ablog configuration
import ablog
extensions = ["ablog"] + extensions
fontawesome_included = True
blog_path = "posts"
blog_title = "Thomas Pethick's blog"
blog_baseurl = "https://pethick.dk/"
blog_feed_archives = True
github_pages = "tmpethick"
post_show_prev_next = False

# Populate publication context for jinja template
import yaml
with open("publications.yml", "r") as stream:
    publications = yaml.safe_load(stream)
jinja_contexts = {
  'publications_ctx': {'publications': publications}
}

# Provide Jinja filter
def format_date(date_string):
    date = datetime.datetime.strptime(date_string, '%Y-%m-%d')
    return date.strftime("%b %d, %Y")

jinja_filters = {
    'format_date': format_date,
}


# Makes footnotes Tufte-style sidenotes
# (see https://sphinx-book-theme.readthedocs.io/en/stable/content-blocks.html?highlight=sidenote#activate-sidenotes-and-marginnotes)
html_theme_options['use_sidenotes'] = True


def _bibtex_escape(value):
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
    }
    return "".join(replacements.get(char, char) for char in value)


def _citation_key(year, slug):
    slug = re.sub(r"^\d{4}-\d{2}-\d{2}-?", "", slug)
    key_slug = re.sub(r"[^A-Za-z0-9]+", "", slug).lower()
    return f"pethick{year}{key_slug}"


def _append_post_citation(app, docname, source):
    if not docname.startswith("posts/") or "/" in docname[len("posts/"):]:
        return

    text = source[0]
    post_match = re.search(r"^```\{post\}\s+(\d{4}-\d{2}-\d{2})", text, re.MULTILINE)
    title_match = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    if not post_match or not title_match:
        return

    date = post_match.group(1)
    year, month, day = date.split("-")
    title = re.sub(r"\s+", " ", title_match.group(1)).strip()
    slug = docname.rsplit("/", 1)[-1]
    baseurl = app.config.blog_baseurl.rstrip("/")
    url = f"{baseurl}/posts/{slug}/"
    bibtex = f"""@misc{{{_citation_key(year, slug)},
  author = {{Thomas Pethick}},
  title = {{{_bibtex_escape(title)}}},
  year = {{{year}}},
  month = {{{month}}},
  day = {{{day}}},
  url = {{{url}}},
  note = {{Blog post}}
}}"""

    source[0] = text.rstrip() + f"""

## Cite this post

```bibtex
{bibtex}
```
"""


def setup(app):
    app.connect("source-read", _append_post_citation)
